// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POC.Data;

namespace POC.Migrations
{
    [DbContext(typeof(POCDbContext))]
    [Migration("20220228023723_initial_Migrations")]
    partial class initial_Migrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("POC.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Answer")
                        .HasColumnType("int");

                    b.Property<string>("Option1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Option2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Option3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Option4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            Answer = 3,
                            Option1 = "Hyper Trainer Marking Language",
                            Option2 = "Hyper Text Marketing Language",
                            Option3 = "Hyper Text Markup Leveler",
                            Option4 = "Hyper Text Markup Language",
                            QuestionText = "What does HTML stand for?"
                        },
                        new
                        {
                            QuestionId = 2,
                            Answer = 3,
                            Option1 = "Charles Babbage",
                            Option2 = "Linus Torvalds",
                            Option3 = "Dennis Ritchie",
                            Option4 = "James Gosling",
                            QuestionText = "Who invented the first computer ?"
                        },
                        new
                        {
                            QuestionId = 3,
                            Answer = 1,
                            Option1 = "1850s",
                            Option2 = "1880s",
                            Option3 = "1930s",
                            Option4 = "1950s",
                            QuestionText = "In which decade was the American Institute of Electrical Engineers (AIEE) founded?"
                        },
                        new
                        {
                            QuestionId = 4,
                            Answer = 1,
                            Option1 = "Report",
                            Option2 = "Field",
                            Option3 = "Record",
                            Option4 = "File",
                            QuestionText = "What is part of a database that holds only one type of information?"
                        },
                        new
                        {
                            QuestionId = 5,
                            Answer = 2,
                            Option1 = "1950s",
                            Option2 = "1960s",
                            Option3 = "1970s",
                            Option4 = "1980s",
                            QuestionText = "In which decade was the SPICE simulator introduced?"
                        },
                        new
                        {
                            QuestionId = 6,
                            Answer = 1,
                            Option1 = "Sound",
                            Option2 = "Remote control",
                            Option3 = "Color balance",
                            Option4 = "High voltage",
                            QuestionText = "Most modern TV's draw power even if turned off. The circuit the power is used in does what function?"
                        },
                        new
                        {
                            QuestionId = 7,
                            Answer = 0,
                            Option1 = "Flash",
                            Option2 = "Flange",
                            Option3 = "Fury",
                            Option4 = "FRAM",
                            QuestionText = "Which is a type of Electrically-Erasable Programmable Read-Only Memory?"
                        },
                        new
                        {
                            QuestionId = 8,
                            Answer = 3,
                            Option1 = "To decrease the current",
                            Option2 = "To increase the current",
                            Option3 = "To decrease the voltage momentarily",
                            Option4 = "To increase the voltage momentarily",
                            QuestionText = "The purpose of choke in tube light is ?"
                        },
                        new
                        {
                            QuestionId = 9,
                            Answer = 0,
                            Option1 = "Alan Turing",
                            Option2 = "Jeff Bezos",
                            Option3 = "George Boole",
                            Option4 = "Charles Babbage",
                            QuestionText = "Who is largely responsible for breaking the German Enigma codes, created a test that provided a foundation for artificial intelligence?"
                        },
                        new
                        {
                            QuestionId = 10,
                            Answer = 1,
                            Option1 = "Dennis Ritchie & Ken Thompson",
                            Option2 = "David Filo & Jerry Yang",
                            Option3 = "Vint Cerf & Robert Kahn",
                            Option4 = "Steve Case & Jeff Bezos",
                            QuestionText = "Who developed Yahoo?"
                        },
                        new
                        {
                            QuestionId = 11,
                            Answer = 2,
                            Option1 = "Choke",
                            Option2 = "Inductor",
                            Option3 = "Resistor",
                            Option4 = "Capacitor",
                            QuestionText = "Made from a variety of materials, such as carbon, which inhibits the flow of current...?"
                        },
                        new
                        {
                            QuestionId = 12,
                            Answer = 0,
                            Option1 = "Video Home System",
                            Option2 = "Very high speed",
                            Option3 = "Video horizontal standard",
                            Option4 = "Voltage house standard",
                            QuestionText = "The most common format for a home video recorder is VHS. VHS stands for...?"
                        },
                        new
                        {
                            QuestionId = 13,
                            Answer = 3,
                            Option1 = "Variant Voltage Vile Frequency",
                            Option2 = "Variable Velocity Variable Fun",
                            Option3 = "Very Very Vicious Frequency",
                            Option4 = "Variable Voltage Variable Frequency",
                            QuestionText = "What does VVVF stand for?"
                        },
                        new
                        {
                            QuestionId = 14,
                            Answer = 3,
                            Option1 = "100 kHz",
                            Option2 = "1 GHz",
                            Option3 = "30 to 300 MHz",
                            Option4 = "3 to 30 MHz",
                            QuestionText = "What frequency range is the High Frequency band?"
                        },
                        new
                        {
                            QuestionId = 15,
                            Answer = 0,
                            Option1 = "Pumping",
                            Option2 = "Exciting",
                            Option3 = "Priming",
                            Option4 = "Raising",
                            QuestionText = "The first step to getting output from a laser is to excite an active medium. What is this process called?"
                        },
                        new
                        {
                            QuestionId = 16,
                            Answer = 2,
                            Option1 = "Permanent magnet motor",
                            Option2 = "Series motor",
                            Option3 = "Squirrel cage motor",
                            Option4 = "Synchronous motor",
                            QuestionText = "Which motor is NOT suitable for use as a DC machine?"
                        },
                        new
                        {
                            QuestionId = 17,
                            Answer = 3,
                            Option1 = "To decrease the current",
                            Option2 = "To increase the current",
                            Option3 = "To decrease the voltage momentarily",
                            Option4 = "To increase the voltage momentarily",
                            QuestionText = "The purpose of choke in tube light is ?"
                        },
                        new
                        {
                            QuestionId = 18,
                            Answer = 2,
                            Option1 = "Programmable Lift Computer",
                            Option2 = "Program List Control",
                            Option3 = "Programmable Logic Controller",
                            Option4 = "Piezo Lamp Connector",
                            QuestionText = "What does the term PLC stand for?"
                        },
                        new
                        {
                            QuestionId = 19,
                            Answer = 0,
                            Option1 = "Database",
                            Option2 = "Double Byte",
                            Option3 = "Data Block",
                            Option4 = "Driver Boot",
                            QuestionText = "'DB' computer abbreviation usually means ?"
                        },
                        new
                        {
                            QuestionId = 20,
                            Answer = 0,
                            Option1 = "Phil Zimmermann",
                            Option2 = "Tim Berners-Lee",
                            Option3 = "Marc Andreessen",
                            Option4 = "Ken Thompson",
                            QuestionText = "Who created Pretty Good Privacy (PGP)?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
